runtime: python39
service: default

# Add this entrypoint:
entrypoint: gunicorn -b :$PORT -k uvicorn.workers.UvicornWorker main:app

handlers:
  # Static assets - for faster serving
  # Consider moving images into assets or adding a handler for /images
  - url: /assets
    static_dir: assets

  # Main application (FastAPI) - handled by the entrypoint
  - url: /.*
    script: auto # 'script: auto' is okay here as the entrypoint overrides the command

env_variables:
  PYTHONUNBUFFERED: "1"

# Optional: Add instance class for better performance if needed
# instance_class: F2