runtime: python39  # Choose the appropriate runtime
service: default

handlers:
  # Index/home page handling
  - url: /index
    static_files: index.html
    upload: index\.html

  - url: /
    static_files: index.html
    upload: index\.html

  # Pages without .html extension
  - url: /(services|process|about|contact)
    static_files: pages/\1.html
    upload: pages/.*\.html

  # Static assets
  - url: /assets/(.*)
    static_files: assets/\1
    upload: assets/(.*)

  # Root level pages
  - url: /(privacy|terms)
    static_files: \1.html
    upload: .*\.html