runtime: python39
service: default

handlers:
  # Static assets - for faster serving
  - url: /assets
    static_dir: assets

  # Direct access to mobile files (to support iframe src)
  - url: /mobile
    static_dir: mobile

  # Main application for templating and dynamic content
  - url: /.*
    script: auto

env_variables:
  PYTHONUNBUFFERED: "1"